# Generated by Django 5.0.6 on 2024-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='prénom',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(default='jean', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
