# Generated by Django 5.0.6 on 2024-05-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0002_remove_enseignant_prénom_enseignant_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('TA', 'Très abîmé'), ('A', 'Abîmé'), ('BE', 'Bon état'), ('N', 'Neuf')], default='N', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='lieu',
            field=models.CharField(default='001', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunt',
            name='objectif_utilisation',
            field=models.TextField(default='Cours', null=True),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='occasion',
            field=models.CharField(default='Cours', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiel',
            name='acheteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiels_achetes', to='prets.enseignant'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='budget',
            field=models.CharField(choices=[('Annuel', 'Budget Annuel'), ('Projet', 'Budget Projet'), ('Financement', 'Financement exceptionnel')], default='Annuel', max_length=50),
        ),
        migrations.AddField(
            model_name='salle',
            name='etage',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_responsable', to='prets.enseignant'),
        ),
        migrations.CreateModel(
            name='EmpruntAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField()),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prets.accessoire')),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prets.emprunt')),
            ],
        ),
        migrations.CreateModel(
            name='MaterielAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prets.accessoire')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prets.materiel')),
            ],
        ),
    ]
