# Generated by Django 5.0.6 on 2024-05-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0004_accessoire_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='occasion',
        ),
    ]
